### ISSUE TITLE
Error while fetching feeds response : <Response [404]>

### ISSUE THREAD

**Issue by mobinhk** [0xSpidey/writeup-miner#1]
why this error show when run a script:

[INF 2024-04-24 08:57:53] loading /home/mobin/hunt/tools/writeup-miner/res/urls.txt file ...
[OK  2024-04-24 08:57:53] File : /home/mobin/hunt/tools/writeup-miner/res/urls.txt loaded successfully.
[INF 2024-04-24 08:57:53] loading filters file : /home/mobin/hunt/tools/writeup-miner/res/filters.txt ..
[OK  2024-04-24 08:57:53] File : /home/mobin/hunt/tools/writeup-miner/res/filters.txt loaded successfully.
[INF 2024-04-24 08:57:53] Loading New Feeds ...
[INF 2024-04-24 08:57:59] https://medium.com/feed/tag/TAGNAME fetched
[ERR 2024-04-24 08:58:04] Error while fetching feeds response : <Response [404]>
[ERR 2024-04-24 08:58:04] Url : https://USERNAME.medium.com/feed
[OK  2024-04-24 08:58:04] New Feeds loaded Successfully

**Comment by Spix0r** [comment]
Because you didn't put any valid url in the urls.txt file

**Comment by mobinhk** [comment]
can you give me a few well known url?

**Comment by Spix0r** [comment]
Examples:
https://medium.com/feed/tag/javascript
https://medium.com/feed/tag/bugbounty
